### ISSUE TITLE
Query string in tweet list api causes 500 error

### ISSUE THREAD

**Issue by wen-wayne-shih** [W-Shih/django-twitter#50]
**Describe the bug**
- Query string in tweet list api causes 500 error

**To Reproduce**
1. Start the server
2. Make a request on tweet list api - GET /api/tweets/?user_id=abc

**Expected behavior**
- Key user_id should have an integer value instead of a string value.
This is a 400 error instead of a 500 error.

**Comment by W-Shih** [comment]
This issue has been fixed
